
customers:
  - user_id: 1
    email: user1@example.com
    password: pass1234
  - user_id: 2
    email: user2@example.com
    password: pass345
  - user_id: 3
    email: user3@example.com
    password: pass678